adobe/helix-theblog-importer

- README.md
- package-lock.json
- package.json
- src/handlers/FastlyHandler.js
- src/index.js
- test/index.test.js
This PR will add a redirect to the `redirects` table of the provided `FASTLY_SERVICE_ID`.
The first entry in the example has been made manually, the second by running `npm test`.
> Fastly Redirect Support

- .circleci/config.yml
- package.json
- src/handlers/FastlyHandler.js
> fix(fastly): use bulkupdate to solve key encoding issue

- src/index.js
> fix(post): remove comment section

- .circleci/config.yml
- package.json
All env properties are missing on the action when deploying with the CI.
> fix(ci): add missing env

- package-lock.json
- package.json
- src/generic/HelixImporter.js
- src/generic/HelixImporterStorageHandler.js
- src/handlers/OneDriveHandler.js
- src/index.js
PR for #3 
Adds capability to check if we need to check if related files (products, topics and author) must be overwritten or not (default is no).
Speed gain (for not overwriting) does not seem to be relevant (less than 10%).
> feat(import): superfluous updates to product md files

- .circleci/config.yml
- .gitignore
- .vscode/launch.json
- package-lock.json
- package.json
- src/generic/BlogHandler.js
- src/generic/HelixImporter.js
- src/handlers/ExcelHandler.js
- src/handlers/FSHandler.js
- src/index.js
- src/tools/CsvFile.js
- src/tools/fullimport.js
> feat(import): Import to drafts/migrated/yyyy/mm/dd

- package-lock.json
- package.json
- src/index.js
> feat(import): handle main topic

- src/index.js
> fix(import): use posted on date as default

- src/index.js
> feat(embeds): Handle more embeds

- src/generic/HelixImporter.js
- src/index.js
- src/tools/fullimport.js
also repaired recording the 301.
> feat(import): more embeds support

- src/generic/HelixImporter.js
- src/index.js
> feat(embed): IA Writer-Style embeds

- package-lock.json
- package.json
- src/generic/HelixImporter.js
- src/index.js
> fix(import): inline elements handling (em and strong)

- src/index.js
Fix #31 
Also fixing missing case for #28 (banners)
> fix(import): iframe embeds and banners with IA Writer style

- src/index.js
> fix(import): embed invalid urls

- src/generic/HelixImporter.js
- src/handlers/ExcelHandler.js
- src/index.js
- src/mappings.js
- src/tools/fullimport.js
> feat(importer): use mapping spreadsheet

- src/index.js
> feat(import): cover more inline elements

- src/index.js
> feat(import): social list

- src/index.js
> feat(import): keep only topic leafs

- src/index.js
> fix(import): remove anti-hero div for legacy design

- src/index.js
Fix #65 and #3 
Import into `/en/publish` and do not override existing product / author / promo / topics files
> feat(import): prod config for importer

- src/generic/HelixImporter.js
> feat(import): use IP instead of domain name

- src/generic/HelixImporter.js
> feat(import): decode filename

- src/generic/HelixImporter.js
- src/index.js
> feat(import): better filename sanitization and existance check
